# -*- coding: utf-8 -*-
"""27thsept2022.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FCSmmZ-AQDp6UM3IymDnqzswz7rc8zft
"""

#to change lower letters
  input_text='\t #sample <html> <h1> #greetings our college offering computer science coUreSes in{B.TECH} wi th 3 SPECIALIZATION & [m.tech] with 1 specialization #computer sCIENCE -->total courses:? https:// www.aec.edu.in is our college  website  !!! </h1> ...\t'
  a= input_text.lower()
  print(a)

#REMOVE NUMBERS
import re
input_text=re.sub(r'\d+', '',input_text)
print(input_text)

#remove white spaces
input_text=input_text.strip()
print(input_text)

#REMOVAL HTML TAGS
import re
html_pattern = re.compile('<.*?>')
input_text = html_pattern.sub(r'' , input_text)
print(input_text)

#removal of urls
url_pattern = re.compile(r'https?://\S+ | www\.\S+')
input_text = url_pattern.sub(r'' ,input_text)
print(input_text)

#removal of hashtags
hash_pattern = re.compile(r'#[a-z]+')
input_text= hash_pattern.sub(r' ', input_text)
print(input_text)

#removal punctuation
import string
for punc in string.punctuation:
  if punc in input_text:
    input_text = input_text.replace(punc, '')
print(input_text)

#removal 
x= re.findall("is our \S+ \S+" , input_text)
input_text = re.sub("is our \S+ \S+", "" , input_text)
print(input_text)

"""##preproccesing steps
1.lowering
2.removing numbers
3.removing  extra vspaces
45.removal of html tags
5.removal of urls
6.removal of hash tags
7.removal orf punchauations
8.removal tokenization
11.removal of frequent words
12.stemming
13.lemmatization
"""